---
version: "3"
services:
  movie:
    container_name: cont1
    image: shaikmustafa/paytm:movie
    ports:
      - "8081:80"

  bus:
    container_name: cont2
    image: shaikmustafa/paytm:bus
    ports:
      - "8082:80"

  bank:
    container_name: cont3
    image: shaikmustafa/paytm:bank
    ports:
      - "8083:80"



---
version: "3"
services:
  dineout:
    container_name: dineout-cont
    build: ./dineout/
    ports:
      - "1111:80"

  food-delivery:
    container_name: food-cont
    build: ./food-delivery
    ports:
      - "2222:80"

  genie:
    container_name: genie-cont
    build: ./genie/
    ports:
      - "3333:80"

  instamart:
    container_name: insta-cont
    build: ./instamart
    ports:
      - "4444:80"

